[tool.poetry]
name = "teals-assignments"
version = "0.1.0"
description = ""
authors = ["classic89 <retrorock8821@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
flask = "^2.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
